Repository openshift-eng/openshift-tests-extension, pull requests merged in 2025-01, with the labels that each got.

#16 Support environment flags which allow for the inclusion/exclusion of test specs when running 'list tests'
  .openshift-tests-extension/openshift_framework_default.json
  .openshift-tests-extension/openshift_payload_example-tests.json
  cmd/example-tests/main.go
  pkg/cmd/cmdlist/list.go
  pkg/extension/extensiontests/environment.go
  pkg/extension/extensiontests/spec.go
  pkg/extension/extensiontests/spec_test.go
  pkg/extension/extensiontests/types.go
  pkg/flags/component.go
  pkg/flags/environment.go
  test/example/example.go
  test/framework/list.go
Labels: approved, tide/merge-method-squash, lgtm

#17 bug: use StringArrayVarP instead of Slice
  pkg/flags/names.go
Labels: approved, lgtm

#19 Add smg247 as OTE approver
  OWNERS
Labels: approved, lgtm

#20 Add images command
  pkg/cmd/cmd.go
  pkg/cmd/cmdimages/cmdimages.go
  pkg/extension/extension.go
  pkg/extension/types.go
Labels: ok-to-test, approved, lgtm
